version: '3.8'

services:
  basic-api:
    container_name: basic-api
    build: 
      context: .
      dockerfile: ./examples/basic/Dockerfile
    ports:
      - "6000:6000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app