version: '3.8'

services:
  flask-api:
    container_name: flask-api
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6000:6000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app